Feaure/tailwindを使って見た目の修正
yuta10200831/6-4.docker-template pull request #5
Opened 2023-08-27 12:08 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/7-dc7f4e386b354d5f92d7d42286f95697
[作成したページのURL(index.php)]
<img width="1714" alt="スクリーンショット 2023-08-27 21 01 33" src="https://github.com/yuta10200831/6-4.docker-template/assets/124555669/666ca862-1c3e-425b-90a6-c45a870b8a4d">

## 作業詳細
以前作成した予約フォームの修正をしましょう。
CSSフレームワークTailwindを使って見た目を整えましょう。

2023-08-27 16:04 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-08-27 16:04 UTC, KatsuyaTanaka95 commented on src/public/complete.php
> +// エラーメッセージの表示
こちらも地図がでるようにしましょう！！
<img width="430" alt="スクリーンショット 2023-08-28 1 04 02" src="https://github.com/yuta10200831/6-4.docker-template/assets/63081802/025aaa1e-0356-495a-957b-8877c629b7a8">

2023-08-28 10:10 UTC, yuta10200831 commented on src/public/complete.php
> +// エラーメッセージの表示
修正済み

2023-08-28 10:11 UTC, yuta10200831 commented
地図の画像が入るように修正しました。
ご確認宜しくお願い致します！

<img width="1714" alt="スクリーンショット 2023-08-28 19 08 54" src="https://github.com/yuta10200831/6-4.docker-template/assets/124555669/c7f8d716-09bf-4324-a4f3-4ec67855ed62">

2023-08-29 03:30 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-08-29 09:41 UTC, merged